### PR TITLE
YAML support, Lastmod command, Optional Autosave

### PR DESCRIPTION
**Pull request by drichardson**
YAML support for #8.

Commit 45dd7a7 uses exe to make the whitespace at the end of the `normal!` command more obvious.

### CODE REVIEW

**Comment by drichardson** [comment]
I've also added commits that:
- make the TOML and YAML key updating code only look for values within the front matter. Before this change, values outside of the front matter could be updated.
- normalize indentation (there were a couple places using different indentation settings)
- add a vim modeline so that future edits use the tab settings in the files

**Comment by drichardson** [comment]
I also added a command called HugoHelperLastmodIsNow to set the `lastmod` front matter key.

**Comment by drichardson** [comment]
@robertbasic Are you taking changes for the repository or is it just a personal thing? Since it was listed at [gohugo](https://gohugo.io/tools/editors/#vim) I was under the impression that it was an actively developed tool.

**Comment by robertbasic** [comment]
Hey! It is actively developed, I just didn't have the time to test your
changes. I do appreciate it though!

**Comment by drichardson** [comment]
OK thanks. I just wanted to make sure I wasn't submitting stuff into the void ;)

**Comment by drichardson** [comment]
Do you have a time frame on when you're going to review this?

**Review by robertbasic — APPROVED** [review]

**Comment by robertbasic** [comment]
Thanks for this, sorry for taking so long!

**Pull request merged**
